name: jejucctv
description: 제주도 CCTV 웹앱

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.6+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2
  video_player: ^0.10.10
  video_player_web_hls:
    path: ./lib/video_player_web_hls-0.1.6
  flutter_linkify: ^3.1.3
  url_launcher: ^5.7.1
  sentry: ">=3.0.0 <4.0.0"
#  http: ^0.12.2
#  file_picker: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
    # - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: Gothic A1
#      fonts:
#        - asset: assets/fonts/GothicA1-Black.ttf
#        - asset: assets/fonts/GothicA1-Bold.ttf
#        - asset: assets/fonts/GothicA1-ExtraBold.ttf
#        - asset: assets/fonts/GothicA1-ExtraLight.ttf
#        - asset: assets/fonts/GothicA1-Light.ttf
#        - asset: assets/fonts/GothicA1-Medium.ttf
#        - asset: assets/fonts/GothicA1-Regular.ttf
#        - asset: assets/fonts/GothicA1-SemiBold.ttf
#        - asset: assets/fonts/GothicA1-Thin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages