name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get

      - name: video_player_web copy
        run: cp -r assets/video_player_web_hls.md $FLUTTER_HOME/.pub-cache/hosted/pub.dartlang.org/video_player_web_hls-0.1.5/lib/video_player_web_hls.dart

      #        uses: canastro/copy-action@0.0.2
#        with:
#          source: assets/video_player_web.dart
#          target: $FLUTTER_HOME/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.3+2/lib/video_player_web.dart

      - run: flutter build web --release

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.JEJU_DEPLOY_TOKEN }}
          publish_dir: ./build/web
          user_name: sh0seo
          user_email: ssh0702@gmail.com 
          commit_message: "update auto"
